#!/bin/bash

function color (){
  echo "\e[$1m$2\e[0m"
}

get_device_model() {
    # 1. Check for ARM/Raspberry Pi Device Tree
    if [[ -f /sys/firmware/devicetree/base/model ]]; then
        tr -d '\0' < /sys/firmware/devicetree/base/model
        echo "" # Add a newline

    # 2. Check for standard x86 PC/Server DMI info
    elif [[ -f /sys/class/dmi/id/sys_vendor && -f /sys/class/dmi/id/product_name ]]; then
        local vendor
        local product
        vendor=$(cat /sys/class/dmi/id/sys_vendor 2>/dev/null)
        product=$(cat /sys/class/dmi/id/product_family 2>/dev/null)
        echo "$vendor $product"

    # 3. Fallback
    else
        echo "Generic Device"
    fi
}

function findDeviceModel (){
  deviceName=""
  local deviceModel=$(tr -d '\0' < /sys/firmware/devicetree/base/model)
  local hostName=$(hostname)

  if [ $hostName ]; then
    deviceName="$deviceModel - $hostName"
  else
    deviceName="$deviceModel"
  fi
}

deviceColor="38;5;16;48;5;249"
greetingsColor="38;5;103"
userColor="38;5;16;48;5;67"
codenameColor="38;5;108"
me=$(logname)
findDeviceModel

# Device Info
deviceLabel=" $(color $deviceColor " $deviceName ")"

# Greetings
me="$(color $userColor " $me ")"
codename="$(grep 'VERSION_CODENAME' /etc/os-release | cut -d '=' -f 2)"
greetings="$(color $greetingsColor " * Welcome") $me $(color $greetingsColor To) $(color $codenameColor $codename)\n"
greetings="$greetings$(color $greetingsColor " * $(date +"%a %b %d %Y, %I:%M:%S %p")")\n"

# OS
greetings="$greetings$(color $greetingsColor " * $(uname -srm | awk '{sub(/\+/, " ", $2); print ""$1" "$2" "$3}')")"

# Print
echo -e "\n$deviceLabel"
echo -e "\n$greetings"
